version: '3.1'
services:
  backend:
    container_name: flask_backend
    build:
      context: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
    links:
      - db:db
    networks:
      - appnetwork

  db:
    image: postgres:latest
    container_name: postgresdb
    hostname: postgresdb
    networks:
      - appnetwork
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    expose:
      - "5432"

networks:
  appnetwork:
    driver: bridge
