version: '3.1'
services:
  backend:
    container_name: flask_backend
    build:
      context: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:alpine3.18
    container_name: postgres_db
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"