version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: NA
      POSTGRES_USER: NA
      POSTGRES_DB: NA
    ports:
      - "5432:5432"
  flask_app:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080